<?xml version="1.0" encoding="utf-8"?><Database Name="Situation" Class="tOreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=IPR-SQL01;Initial Catalog=Situation;Persist Security Info=True;User ID=usercataloghi" SettingsObjectName="COSiFa.My.MySettings" SettingsPropertyName="SituationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tOre" Member="tOre">
    <Type Name="tOre">
      <Column Name="Id" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Catalogo" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="OreSap" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" CanBeNull="false" />
      <Column Name="OreDisegno" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" CanBeNull="false" />
      <Column Name="Utente" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>