'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.18444
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Situation")>  _
Partial Public Class tSituazioneDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Definizioni metodo Extensibility"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.COSiFa.My.MySettings.Default.SituationConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property tSituazione() As System.Data.Linq.Table(Of tSituazione)
		Get
			Return Me.GetTable(Of tSituazione)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tSituazione")>  _
Partial Public Class tSituazione
	
	Private _Anno As Integer
	
	Private _Produttore As String
	
	Private _Equipment As String
	
	Private _SettoreCommerciale As String
	
	Private _CanaleDistributivo As String
	
	Private _OdV As String
	
	Private _CodiceCliente As String
	
	Private _AnagraficaCliente As String
	
	Private _Nazione As String
	
	Private _Posizione As Integer
	
	Private _CodiceMateriale As String
	
	Private _AnagraficaMateriale As String
	
	Private _SituazioneSpedizione As String
	
	Private _DataSpedizione As Date
	
	Private _DtSped1 As System.Nullable(Of Date)
	
	Private _DtSped2 As System.Nullable(Of Date)
	
	Private _Autore As String
	
	Private _Note As String
	
	Private _RifProgramma As String
	
	Private _DataUscita As Date
	
	Private _DataConsegnaPrevista As Date
	
	Private _Studio As String
	
	Private _CentroDiCosto As Long
	
	Private _OdA As String
	
	Private _PosizioneOdA As String
	
	Private _Catalogo As String
	
	Private _DataArchiviazione As System.Nullable(Of Date)
	
	Private _NumeroArchiviazione As String
	
	Private _NumeroArchiviazioneTavole As String
	
	Private _OreSAP As System.Nullable(Of Decimal)
	
	Private _OreDisegno As System.Nullable(Of Decimal)
	
	Private _CostoFatturato As String
	
	Private _CostoPrevisto As String
	
	Private _Scostamento As String
	
	Private _NoteAgg As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Anno", DbType:="Int NOT NULL")>  _
	Public Property Anno() As Integer
		Get
			Return Me._Anno
		End Get
		Set
			If ((Me._Anno = value)  _
						= false) Then
				Me._Anno = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Produttore", DbType:="VarChar(10)")>  _
	Public Property Produttore() As String
		Get
			Return Me._Produttore
		End Get
		Set
			If (String.Equals(Me._Produttore, value) = false) Then
				Me._Produttore = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Equipment", DbType:="VarChar(8) NOT NULL", CanBeNull:=false)>  _
	Public Property Equipment() As String
		Get
			Return Me._Equipment
		End Get
		Set
			If (String.Equals(Me._Equipment, value) = false) Then
				Me._Equipment = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SettoreCommerciale", DbType:="VarChar(2) NOT NULL", CanBeNull:=false)>  _
	Public Property SettoreCommerciale() As String
		Get
			Return Me._SettoreCommerciale
		End Get
		Set
			If (String.Equals(Me._SettoreCommerciale, value) = false) Then
				Me._SettoreCommerciale = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CanaleDistributivo", DbType:="VarChar(2) NOT NULL", CanBeNull:=false)>  _
	Public Property CanaleDistributivo() As String
		Get
			Return Me._CanaleDistributivo
		End Get
		Set
			If (String.Equals(Me._CanaleDistributivo, value) = false) Then
				Me._CanaleDistributivo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OdV", DbType:="VarChar(18) NOT NULL", CanBeNull:=false)>  _
	Public Property OdV() As String
		Get
			Return Me._OdV
		End Get
		Set
			If (String.Equals(Me._OdV, value) = false) Then
				Me._OdV = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CodiceCliente", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property CodiceCliente() As String
		Get
			Return Me._CodiceCliente
		End Get
		Set
			If (String.Equals(Me._CodiceCliente, value) = false) Then
				Me._CodiceCliente = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AnagraficaCliente", DbType:="VarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property AnagraficaCliente() As String
		Get
			Return Me._AnagraficaCliente
		End Get
		Set
			If (String.Equals(Me._AnagraficaCliente, value) = false) Then
				Me._AnagraficaCliente = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Nazione", DbType:="VarChar(2) NOT NULL", CanBeNull:=false)>  _
	Public Property Nazione() As String
		Get
			Return Me._Nazione
		End Get
		Set
			If (String.Equals(Me._Nazione, value) = false) Then
				Me._Nazione = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Posizione", DbType:="Int NOT NULL")>  _
	Public Property Posizione() As Integer
		Get
			Return Me._Posizione
		End Get
		Set
			If ((Me._Posizione = value)  _
						= false) Then
				Me._Posizione = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CodiceMateriale", DbType:="VarChar(15) NOT NULL", CanBeNull:=false)>  _
	Public Property CodiceMateriale() As String
		Get
			Return Me._CodiceMateriale
		End Get
		Set
			If (String.Equals(Me._CodiceMateriale, value) = false) Then
				Me._CodiceMateriale = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AnagraficaMateriale", DbType:="VarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property AnagraficaMateriale() As String
		Get
			Return Me._AnagraficaMateriale
		End Get
		Set
			If (String.Equals(Me._AnagraficaMateriale, value) = false) Then
				Me._AnagraficaMateriale = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SituazioneSpedizione", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property SituazioneSpedizione() As String
		Get
			Return Me._SituazioneSpedizione
		End Get
		Set
			If (String.Equals(Me._SituazioneSpedizione, value) = false) Then
				Me._SituazioneSpedizione = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataSpedizione", DbType:="Date NOT NULL")>  _
	Public Property DataSpedizione() As Date
		Get
			Return Me._DataSpedizione
		End Get
		Set
			If ((Me._DataSpedizione = value)  _
						= false) Then
				Me._DataSpedizione = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DtSped1", DbType:="Date")>  _
	Public Property DtSped1() As System.Nullable(Of Date)
		Get
			Return Me._DtSped1
		End Get
		Set
			If (Me._DtSped1.Equals(value) = false) Then
				Me._DtSped1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DtSped2", DbType:="Date")>  _
	Public Property DtSped2() As System.Nullable(Of Date)
		Get
			Return Me._DtSped2
		End Get
		Set
			If (Me._DtSped2.Equals(value) = false) Then
				Me._DtSped2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Autore", DbType:="VarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property Autore() As String
		Get
			Return Me._Autore
		End Get
		Set
			If (String.Equals(Me._Autore, value) = false) Then
				Me._Autore = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Note", DbType:="VarChar(255)")>  _
	Public Property Note() As String
		Get
			Return Me._Note
		End Get
		Set
			If (String.Equals(Me._Note, value) = false) Then
				Me._Note = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RifProgramma", DbType:="VarChar(7) NOT NULL", CanBeNull:=false)>  _
	Public Property RifProgramma() As String
		Get
			Return Me._RifProgramma
		End Get
		Set
			If (String.Equals(Me._RifProgramma, value) = false) Then
				Me._RifProgramma = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataUscita", DbType:="Date NOT NULL")>  _
	Public Property DataUscita() As Date
		Get
			Return Me._DataUscita
		End Get
		Set
			If ((Me._DataUscita = value)  _
						= false) Then
				Me._DataUscita = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataConsegnaPrevista", DbType:="Date NOT NULL")>  _
	Public Property DataConsegnaPrevista() As Date
		Get
			Return Me._DataConsegnaPrevista
		End Get
		Set
			If ((Me._DataConsegnaPrevista = value)  _
						= false) Then
				Me._DataConsegnaPrevista = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Studio", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property Studio() As String
		Get
			Return Me._Studio
		End Get
		Set
			If (String.Equals(Me._Studio, value) = false) Then
				Me._Studio = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CentroDiCosto", DbType:="BigInt NOT NULL")>  _
	Public Property CentroDiCosto() As Long
		Get
			Return Me._CentroDiCosto
		End Get
		Set
			If ((Me._CentroDiCosto = value)  _
						= false) Then
				Me._CentroDiCosto = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OdA", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property OdA() As String
		Get
			Return Me._OdA
		End Get
		Set
			If (String.Equals(Me._OdA, value) = false) Then
				Me._OdA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PosizioneOdA", DbType:="VarChar(12) NOT NULL", CanBeNull:=false)>  _
	Public Property PosizioneOdA() As String
		Get
			Return Me._PosizioneOdA
		End Get
		Set
			If (String.Equals(Me._PosizioneOdA, value) = false) Then
				Me._PosizioneOdA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Catalogo", DbType:="VarChar(10)")>  _
	Public Property Catalogo() As String
		Get
			Return Me._Catalogo
		End Get
		Set
			If (String.Equals(Me._Catalogo, value) = false) Then
				Me._Catalogo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DataArchiviazione", DbType:="Date")>  _
	Public Property DataArchiviazione() As System.Nullable(Of Date)
		Get
			Return Me._DataArchiviazione
		End Get
		Set
			If (Me._DataArchiviazione.Equals(value) = false) Then
				Me._DataArchiviazione = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NumeroArchiviazione", DbType:="VarChar(20)")>  _
	Public Property NumeroArchiviazione() As String
		Get
			Return Me._NumeroArchiviazione
		End Get
		Set
			If (String.Equals(Me._NumeroArchiviazione, value) = false) Then
				Me._NumeroArchiviazione = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NumeroArchiviazioneTavole", DbType:="VarChar(20)")>  _
	Public Property NumeroArchiviazioneTavole() As String
		Get
			Return Me._NumeroArchiviazioneTavole
		End Get
		Set
			If (String.Equals(Me._NumeroArchiviazioneTavole, value) = false) Then
				Me._NumeroArchiviazioneTavole = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OreSAP", DbType:="Decimal(4,1)")>  _
	Public Property OreSAP() As System.Nullable(Of Decimal)
		Get
			Return Me._OreSAP
		End Get
		Set
			If (Me._OreSAP.Equals(value) = false) Then
				Me._OreSAP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OreDisegno", DbType:="Decimal(4,1)")>  _
	Public Property OreDisegno() As System.Nullable(Of Decimal)
		Get
			Return Me._OreDisegno
		End Get
		Set
			If (Me._OreDisegno.Equals(value) = false) Then
				Me._OreDisegno = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CostoFatturato", DbType:="NChar(10)")>  _
	Public Property CostoFatturato() As String
		Get
			Return Me._CostoFatturato
		End Get
		Set
			If (String.Equals(Me._CostoFatturato, value) = false) Then
				Me._CostoFatturato = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CostoPrevisto", DbType:="NChar(10)")>  _
	Public Property CostoPrevisto() As String
		Get
			Return Me._CostoPrevisto
		End Get
		Set
			If (String.Equals(Me._CostoPrevisto, value) = false) Then
				Me._CostoPrevisto = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Scostamento", DbType:="NChar(10)")>  _
	Public Property Scostamento() As String
		Get
			Return Me._Scostamento
		End Get
		Set
			If (String.Equals(Me._Scostamento, value) = false) Then
				Me._Scostamento = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NoteAgg", DbType:="VarChar(255)")>  _
	Public Property NoteAgg() As String
		Get
			Return Me._NoteAgg
		End Get
		Set
			If (String.Equals(Me._NoteAgg, value) = false) Then
				Me._NoteAgg = value
			End If
		End Set
	End Property
End Class
